import { PrismaClient } from '@prisma/client';

import { auth } from '../src/shared/auth/auth';
import { env } from '../src/shared/config/env';
import { computeDedupeKey } from '../src/modules/activities/domain/computeDedupeKey';
import { computeExpiresAt, computeRecheckAfter } from '../src/modules/activities/domain/freshness';

const prisma = new PrismaClient();

type ActivityCategory = 'SPORT' | 'ROMANTIC' | 'FOOD' | 'CULTURE' | 'OUTDOOR' | 'NIGHTLIFE';

type SeedActivity = {
  slug: string;
  title: string;
  description: string;
  imageUrl: string;
  kind: 'EVENT' | 'PLACE';
  categories: { primary: ActivityCategory; secondary: ActivityCategory[] };
  address: string;
  neighborhood: string;
  latitude: number;
  longitude: number;
  dateStart: Date | null;
  dateEnd: Date | null;
  priceMinCents: number;
  priceMaxCents: number | null;
  externalUrl: string;
  indoor: boolean;
  outdoor: boolean;
  isFeatured: boolean;
};

const eventActivities: SeedActivity[] = [
  {
    slug: 'mural-festival-2026',
    title: 'MURAL Festival',
    description: 'Murals, block parties, and open-air music along Saint-Laurent.',
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
    kind: 'EVENT',
    categories: { primary: 'CULTURE', secondary: [] },
    address: 'Boulevard Saint-Laurent, Montreal, QC',
    neighborhood: 'Plateau-Mont-Royal',
    latitude: 45.5162,
    longitude: -73.5817,
    dateStart: new Date('2026-06-04T16:00:00.000Z'),
    dateEnd: new Date('2026-06-14T03:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 3500,
    externalUrl: 'https://www.muralfestival.com/',
    indoor: false,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'montreal-jazz-festival-2026',
    title: 'Montreal Jazz Festival',
    description: 'Downtown stages, late sets, and a dense summer music program.',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063',
    kind: 'EVENT',
    categories: { primary: 'NIGHTLIFE', secondary: [] },
    address: 'Quartier des Spectacles, Montreal, QC',
    neighborhood: 'Quartier des Spectacles',
    latitude: 45.509,
    longitude: -73.566,
    dateStart: new Date('2026-06-25T21:00:00.000Z'),
    dateEnd: new Date('2026-07-05T03:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 12500,
    externalUrl: 'https://www.montrealjazzfest.com/',
    indoor: true,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'just-for-laughs-2026',
    title: 'Just for Laughs',
    description: 'Comedy showcases and outdoor downtown festival energy.',
    imageUrl: 'https://images.unsplash.com/photo-1527224538127-2104bb71c51b',
    kind: 'EVENT',
    categories: { primary: 'CULTURE', secondary: [] },
    address: 'Place des Festivals, Montreal, QC',
    neighborhood: 'Quartier des Spectacles',
    latitude: 45.5098,
    longitude: -73.5654,
    dateStart: new Date('2026-07-15T22:00:00.000Z'),
    dateEnd: new Date('2026-07-26T03:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 9000,
    externalUrl: 'https://www.hahaha.com/',
    indoor: true,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'osheaga-2026',
    title: 'Osheaga',
    description: 'Three days of festival sets at Parc Jean-Drapeau.',
    imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
    kind: 'EVENT',
    categories: { primary: 'NIGHTLIFE', secondary: [] },
    address: 'Parc Jean-Drapeau, Montreal, QC',
    neighborhood: 'Parc Jean-Drapeau',
    latitude: 45.5086,
    longitude: -73.5269,
    dateStart: new Date('2026-07-31T18:00:00.000Z'),
    dateEnd: new Date('2026-08-03T03:30:00.000Z'),
    priceMinCents: 16500,
    priceMaxCents: 42500,
    externalUrl: 'https://osheaga.com/',
    indoor: false,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'grand-prix-weekend-2026',
    title: 'Grand Prix Weekend',
    description: 'Race weekend watch parties, terraces, and downtown street events.',
    imageUrl: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d',
    kind: 'EVENT',
    categories: { primary: 'SPORT', secondary: [] },
    address: 'Circuit Gilles-Villeneuve, Montreal, QC',
    neighborhood: 'Parc Jean-Drapeau',
    latitude: 45.5001,
    longitude: -73.5225,
    dateStart: new Date('2026-06-05T14:00:00.000Z'),
    dateEnd: new Date('2026-06-07T22:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 30000,
    externalUrl: 'https://www.gpcanada.ca/',
    indoor: false,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'tam-tams-sunday-circle',
    title: 'Tam-Tams Sunday Circle',
    description: 'Drums, picnic blankets, and a slow Sunday at the mountain.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f',
    kind: 'EVENT',
    categories: { primary: 'OUTDOOR', secondary: [] },
    address: 'George-Etienne Cartier Monument, Montreal, QC',
    neighborhood: 'Plateau-Mont-Royal',
    latitude: 45.5145,
    longitude: -73.585,
    dateStart: new Date('2026-05-17T17:00:00.000Z'),
    dateEnd: new Date('2026-05-17T22:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://www.mtl.org/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'piknic-electronik-2026',
    title: 'Piknic Electronik',
    description: 'Open-air electronic music on the island.',
    imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a',
    kind: 'EVENT',
    categories: { primary: 'NIGHTLIFE', secondary: [] },
    address: 'Plaine des jeux, Parc Jean-Drapeau, Montreal, QC',
    neighborhood: 'Parc Jean-Drapeau',
    latitude: 45.5121,
    longitude: -73.5311,
    dateStart: new Date('2026-05-24T18:00:00.000Z'),
    dateEnd: new Date('2026-05-25T02:00:00.000Z'),
    priceMinCents: 2400,
    priceMaxCents: 4200,
    externalUrl: 'https://piknicelectronik.com/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'bota-bota-twilight-spa',
    title: 'Bota Bota Twilight Spa',
    description: 'Evening thermal circuit on the river with skyline views.',
    imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef',
    kind: 'EVENT',
    categories: { primary: 'ROMANTIC', secondary: [] },
    address: 'Bota Bota, Old Port of Montreal, QC',
    neighborhood: 'Vieux-Port',
    latitude: 45.5014,
    longitude: -73.5496,
    dateStart: new Date('2026-06-12T22:30:00.000Z'),
    dateEnd: new Date('2026-06-13T01:30:00.000Z'),
    priceMinCents: 8500,
    priceMaxCents: 12500,
    externalUrl: 'https://botabota.ca/',
    indoor: true,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'atwater-market-tasting-walk',
    title: 'Atwater Market Tasting Walk',
    description: 'Cheese, fruit, pastries, and canal-side snacking.',
    imageUrl: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9',
    kind: 'EVENT',
    categories: { primary: 'FOOD', secondary: [] },
    address: 'Atwater Market, Montreal, QC',
    neighborhood: 'Saint-Henri',
    latitude: 45.4792,
    longitude: -73.5777,
    dateStart: new Date('2026-05-23T15:00:00.000Z'),
    dateEnd: new Date('2026-05-23T18:00:00.000Z'),
    priceMinCents: 1500,
    priceMaxCents: 4500,
    externalUrl: 'https://www.marchespublics-mtl.com/',
    indoor: true,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'verdun-river-run',
    title: 'Verdun River Run',
    description: 'A relaxed 5K along the St. Lawrence with coffee after.',
    imageUrl: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8',
    kind: 'EVENT',
    categories: { primary: 'SPORT', secondary: [] },
    address: 'Promenade Wellington, Montreal, QC',
    neighborhood: 'Verdun',
    latitude: 45.4595,
    longitude: -73.5672,
    dateStart: new Date('2026-05-30T13:00:00.000Z'),
    dateEnd: new Date('2026-05-30T15:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://www.mtl.org/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'cinema-du-parc-retro-night',
    title: 'Cinema du Parc Retro Night',
    description: 'A cozy repertory screening near McGill.',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    kind: 'EVENT',
    categories: { primary: 'CULTURE', secondary: [] },
    address: '3575 Avenue du Parc, Montreal, QC',
    neighborhood: 'Milton-Parc',
    latitude: 45.5097,
    longitude: -73.5728,
    dateStart: new Date('2026-06-18T23:00:00.000Z'),
    dateEnd: new Date('2026-06-19T01:30:00.000Z'),
    priceMinCents: 1300,
    priceMaxCents: 1800,
    externalUrl: 'https://www.cinemaduparc.com/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'lachine-canal-bike-loop',
    title: 'Lachine Canal Bike Loop',
    description: 'A canal ride from Saint-Henri toward the west end.',
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e',
    kind: 'EVENT',
    categories: { primary: 'SPORT', secondary: [] },
    address: 'Lachine Canal National Historic Site, Montreal, QC',
    neighborhood: 'Saint-Henri',
    latitude: 45.4807,
    longitude: -73.5759,
    dateStart: new Date('2026-06-21T14:00:00.000Z'),
    dateEnd: new Date('2026-06-21T17:00:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 3000,
    externalUrl: 'https://parks.canada.ca/lhn-nhs/qc/canallachine',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'little-italy-supper-crawl',
    title: 'Little Italy Supper Crawl',
    description: 'A pasta, wine, and gelato route around Dante Park.',
    imageUrl: 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b',
    kind: 'EVENT',
    categories: { primary: 'FOOD', secondary: [] },
    address: 'Dante Park, Montreal, QC',
    neighborhood: 'Petite-Italie',
    latitude: 45.5322,
    longitude: -73.6133,
    dateStart: new Date('2026-06-27T22:00:00.000Z'),
    dateEnd: new Date('2026-06-28T02:00:00.000Z'),
    priceMinCents: 3500,
    priceMaxCents: 9000,
    externalUrl: 'https://www.mtl.org/',
    indoor: true,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'old-port-fireworks-night',
    title: 'Old Port Fireworks Night',
    description: 'A waterfront evening for the international fireworks season.',
    imageUrl: 'https://images.unsplash.com/photo-1533236897111-3e94666b2edf',
    kind: 'EVENT',
    categories: { primary: 'ROMANTIC', secondary: [] },
    address: 'Old Port of Montreal, Montreal, QC',
    neighborhood: 'Vieux-Port',
    latitude: 45.506,
    longitude: -73.549,
    dateStart: new Date('2026-07-04T23:30:00.000Z'),
    dateEnd: new Date('2026-07-05T02:30:00.000Z'),
    priceMinCents: 0,
    priceMaxCents: 4000,
    externalUrl: 'https://www.mtl.org/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'jean-talon-market-brunch',
    title: 'Jean-Talon Market Brunch',
    description: 'A slow market morning built around bakeries and seasonal produce.',
    imageUrl: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0',
    kind: 'EVENT',
    categories: { primary: 'FOOD', secondary: [] },
    address: 'Jean-Talon Market, Montreal, QC',
    neighborhood: 'Petite-Italie',
    latitude: 45.5354,
    longitude: -73.6155,
    dateStart: new Date('2026-07-11T14:00:00.000Z'),
    dateEnd: new Date('2026-07-11T17:00:00.000Z'),
    priceMinCents: 1000,
    priceMaxCents: 4500,
    externalUrl: 'https://www.marchespublics-mtl.com/',
    indoor: true,
    outdoor: true,
    isFeatured: false,
  },
];

const placeActivities: SeedActivity[] = [
  {
    slug: 'mount-royal-lookout',
    title: 'Mount Royal Lookout',
    description: 'The classic skyline view, best paired with a walk through the park.',
    imageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
    kind: 'PLACE',
    categories: { primary: 'OUTDOOR', secondary: [] },
    address: 'Kondiaronk Belvedere, Montreal, QC',
    neighborhood: 'Plateau-Mont-Royal',
    latitude: 45.5036,
    longitude: -73.5871,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://www.lemontroyal.qc.ca/',
    indoor: false,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'bota-bota',
    title: 'Bota Bota',
    description: 'A floating spa in the Old Port for thermal circuits and river views.',
    imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
    kind: 'PLACE',
    categories: { primary: 'ROMANTIC', secondary: ['OUTDOOR'] },
    address: 'Corner de la Commune W. and McGill, Montreal, QC',
    neighborhood: 'Vieux-Port',
    latitude: 45.5014,
    longitude: -73.5496,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 8500,
    priceMaxCents: 15000,
    externalUrl: 'https://botabota.ca/',
    indoor: true,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'jardin-botanique',
    title: 'Jardin botanique',
    description: 'Greenhouses, themed gardens, and long walks near the Olympic Park.',
    imageUrl: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735',
    kind: 'PLACE',
    categories: { primary: 'CULTURE', secondary: ['OUTDOOR'] },
    address: '4101 Rue Sherbrooke E, Montreal, QC',
    neighborhood: 'Hochelaga-Maisonneuve',
    latitude: 45.5579,
    longitude: -73.5565,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 1750,
    priceMaxCents: 2350,
    externalUrl: 'https://espacepourlavie.ca/jardin-botanique',
    indoor: true,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'sat',
    title: 'Societe des arts technologiques',
    description: 'Immersive shows, electronic nights, and a rooftop in summer.',
    imageUrl: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455',
    kind: 'PLACE',
    categories: { primary: 'NIGHTLIFE', secondary: [] },
    address: '1201 Boulevard Saint-Laurent, Montreal, QC',
    neighborhood: 'Quartier des Spectacles',
    latitude: 45.5094,
    longitude: -73.5622,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 1800,
    priceMaxCents: 6500,
    externalUrl: 'https://sat.qc.ca/',
    indoor: true,
    outdoor: true,
    isFeatured: true,
  },
  {
    slug: 'st-viateur-bagel',
    title: 'St-Viateur Bagel',
    description: 'Warm bagels from the oven in the heart of Mile End.',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
    kind: 'PLACE',
    categories: { primary: 'FOOD', secondary: [] },
    address: '263 Rue Saint-Viateur O, Montreal, QC',
    neighborhood: 'Mile End',
    latitude: 45.5227,
    longitude: -73.6016,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 200,
    priceMaxCents: 2500,
    externalUrl: 'https://www.stviateurbagel.com/',
    indoor: true,
    outdoor: false,
    isFeatured: true,
  },
  {
    slug: 'crew-collective-cafe',
    title: 'Crew Collective Cafe',
    description: 'A grand banking hall turned cafe and coworking room.',
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2',
    kind: 'PLACE',
    categories: { primary: 'FOOD', secondary: [] },
    address: '360 Rue Saint-Jacques, Montreal, QC',
    neighborhood: 'Vieux-Montreal',
    latitude: 45.5018,
    longitude: -73.5595,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 500,
    priceMaxCents: 3000,
    externalUrl: 'https://crewcollectivecafe.com/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'lachine-canal',
    title: 'Lachine Canal',
    description: 'Bike paths, picnic stops, and canal-side golden hour.',
    imageUrl: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
    kind: 'PLACE',
    categories: { primary: 'OUTDOOR', secondary: [] },
    address: 'Lachine Canal, Montreal, QC',
    neighborhood: 'Saint-Henri',
    latitude: 45.4808,
    longitude: -73.5758,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://parks.canada.ca/lhn-nhs/qc/canallachine',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'verdun-beach',
    title: 'Verdun Beach',
    description: 'A compact city beach beside the river and bike path.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e',
    kind: 'PLACE',
    categories: { primary: 'OUTDOOR', secondary: [] },
    address: '4110 Boulevard LaSalle, Montreal, QC',
    neighborhood: 'Verdun',
    latitude: 45.4505,
    longitude: -73.5672,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://montreal.ca/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'dinette-triple-crown',
    title: 'Dinette Triple Crown',
    description: 'Southern comfort food with picnic baskets for the park nearby.',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
    kind: 'PLACE',
    categories: { primary: 'FOOD', secondary: [] },
    address: '6704 Rue Clark, Montreal, QC',
    neighborhood: 'Petite-Italie',
    latitude: 45.5317,
    longitude: -73.6111,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 1800,
    priceMaxCents: 5500,
    externalUrl: 'https://www.dinettetriplecrown.com/',
    indoor: true,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'cinema-moderne',
    title: 'Cinema Moderne',
    description: 'Small-room cinema with a sharp program and a cafe-bar.',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba',
    kind: 'PLACE',
    categories: { primary: 'CULTURE', secondary: [] },
    address: '5150 Boulevard Saint-Laurent, Montreal, QC',
    neighborhood: 'Mile End',
    latitude: 45.5238,
    longitude: -73.5945,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 1300,
    priceMaxCents: 2200,
    externalUrl: 'https://www.cinemamoderne.com/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'allez-up',
    title: 'Allez Up',
    description: 'Climbing and bouldering in converted industrial spaces.',
    imageUrl: 'https://images.unsplash.com/photo-1522163182402-834f871fd851',
    kind: 'PLACE',
    categories: { primary: 'SPORT', secondary: [] },
    address: '1555 Rue Saint-Patrick, Montreal, QC',
    neighborhood: 'Pointe-Saint-Charles',
    latitude: 45.4805,
    longitude: -73.5609,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 2300,
    priceMaxCents: 3200,
    externalUrl: 'https://allezup.com/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'maison-boulud',
    title: 'Maison Boulud',
    description: 'Polished dinner service for a special night downtown.',
    imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
    kind: 'PLACE',
    categories: { primary: 'FOOD', secondary: ['ROMANTIC'] },
    address: '1228 Rue Sherbrooke O, Montreal, QC',
    neighborhood: 'Golden Square Mile',
    latitude: 45.5004,
    longitude: -73.5789,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 6500,
    priceMaxCents: 18000,
    externalUrl: 'https://www.maisonboulud.com/montreal/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'parc-jean-drapeau',
    title: 'Parc Jean-Drapeau',
    description: 'Island paths, waterfront views, public art, and festival grounds.',
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
    kind: 'PLACE',
    categories: { primary: 'OUTDOOR', secondary: [] },
    address: 'Parc Jean-Drapeau, Montreal, QC',
    neighborhood: 'Parc Jean-Drapeau',
    latitude: 45.5088,
    longitude: -73.5264,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 0,
    priceMaxCents: null,
    externalUrl: 'https://www.parcjeandrapeau.com/',
    indoor: false,
    outdoor: true,
    isFeatured: false,
  },
  {
    slug: 'phi-centre',
    title: 'PHI Centre',
    description: 'Exhibitions, immersive work, screenings, and intimate shows.',
    imageUrl: 'https://images.unsplash.com/photo-1545987796-200677ee1011',
    kind: 'PLACE',
    categories: { primary: 'CULTURE', secondary: [] },
    address: '407 Rue Saint-Pierre, Montreal, QC',
    neighborhood: 'Vieux-Montreal',
    latitude: 45.5021,
    longitude: -73.5554,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 0,
    priceMaxCents: 4500,
    externalUrl: 'https://phi.ca/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
  {
    slug: 'dieu-du-ciel',
    title: 'Dieu du Ciel',
    description: 'A Mile End brewpub for low-key evenings and strong local taps.',
    imageUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b',
    kind: 'PLACE',
    categories: { primary: 'NIGHTLIFE', secondary: [] },
    address: '29 Avenue Laurier O, Montreal, QC',
    neighborhood: 'Mile End',
    latitude: 45.5223,
    longitude: -73.5944,
    dateStart: null,
    dateEnd: null,
    priceMinCents: 800,
    priceMaxCents: 4500,
    externalUrl: 'https://dieuduciel.com/',
    indoor: true,
    outdoor: false,
    isFeatured: false,
  },
];

const affinities = [
  { category: 'SPORT' as const, score: 8 },
  { category: 'FOOD' as const, score: 9 },
  { category: 'ROMANTIC' as const, score: 3 },
  { category: 'CULTURE' as const, score: 6 },
  { category: 'OUTDOOR' as const, score: 7 },
  { category: 'NIGHTLIFE' as const, score: 4 },
];

async function main() {
  const montreal = await prisma.city.upsert({
    where: { slug: 'montreal' },
    update: {},
    create: {
      slug: 'montreal',
      name: 'Montréal',
      country: 'CA',
      timezone: 'America/Toronto',
      centerLat: 45.5019,
      centerLng: -73.5674,
      bboxMinLat: 45.4,
      bboxMinLng: -73.98,
      bboxMaxLat: 45.71,
      bboxMaxLng: -73.47,
    },
  });

  // Recreate the seed user through the real Better Auth sign-up path so it has
  // a credential Account (scrypt password) exactly like a normal signup —
  // single inscription code-path in the repo. Idempotent: nuke first.
  const existing = await prisma.user.findUnique({
    where: { email: env.SEED_USER_EMAIL },
    select: { id: true },
  });
  if (existing) {
    await prisma.userCategoryAffinity.deleteMany({ where: { userId: existing.id } });
    await prisma.favorite.deleteMany({ where: { userId: existing.id } });
    await prisma.calendarEntry.deleteMany({ where: { userId: existing.id } });
    await prisma.user.delete({ where: { id: existing.id } }); // cascades Account/Session
  }

  // databaseHooks.user.create.before injects cityId = Montréal (created above).
  await auth.api.signUpEmail({
    body: {
      email: env.SEED_USER_EMAIL,
      password: env.SEED_USER_PASSWORD,
      name: env.SEED_USER_NAME,
    },
  });

  // Backfill the business fields Better Auth doesn't manage, and mark Hugo as
  // already onboarded so he skips the popup.
  const user = await prisma.user.update({
    where: { email: env.SEED_USER_EMAIL },
    data: {
      gender: 'MALE',
      birthDate: new Date('2000-06-28'),
      onboardedAt: new Date(),
    },
  });

  const source = await prisma.source.upsert({
    where: { name: 'manual' },
    update: {},
    create: { name: 'manual' },
  });

  const seedNow = new Date();
  for (const activity of [...eventActivities, ...placeActivities]) {
    const dedupeKey = computeDedupeKey({
      kind: activity.kind,
      title: activity.title,
      dateStart: activity.dateStart,
      latitude: activity.latitude,
      longitude: activity.longitude,
    });
    const expiresAt = computeExpiresAt({ kind: activity.kind, dateEnd: activity.dateEnd });
    const recheckAfter = computeRecheckAfter({ kind: activity.kind, lastSeenAt: seedNow });

    await prisma.activity.upsert({
      where: {
        cityId_dedupeKey: {
          cityId: montreal.id,
          dedupeKey,
        },
      },
      update: {
        slug: activity.slug,
        title: activity.title,
        description: activity.description,
        imageUrl: activity.imageUrl,
        kind: activity.kind,
        categories: activity.categories,
        address: activity.address,
        neighborhood: activity.neighborhood,
        latitude: activity.latitude,
        longitude: activity.longitude,
        dateStart: activity.dateStart,
        dateEnd: activity.dateEnd,
        priceMinCents: activity.priceMinCents,
        priceMaxCents: activity.priceMaxCents,
        externalUrl: activity.externalUrl,
        indoor: activity.indoor,
        outdoor: activity.outdoor,
        isFeatured: activity.isFeatured,
        status: 'PUBLISHED',
        cityId: montreal.id,
        dedupeKey,
        expiresAt,
        lastSeenAt: seedNow,
        lastVerifiedAt: seedNow,
        recheckAfter,
      },
      create: {
        ...activity,
        status: 'PUBLISHED',
        sourceId: source.id,
        cityId: montreal.id,
        dedupeKey,
        expiresAt,
        lastSeenAt: seedNow,
        lastVerifiedAt: seedNow,
        recheckAfter,
      },
    });
  }

  for (const affinity of affinities) {
    await prisma.userCategoryAffinity.upsert({
      where: {
        userId_category: {
          userId: user.id,
          category: affinity.category,
        },
      },
      update: { score: affinity.score },
      create: {
        userId: user.id,
        category: affinity.category,
        score: affinity.score,
      },
    });
  }

  const [
    userCount,
    sourceCount,
    activityCount,
    eventCount,
    placeCount,
    featuredEventCount,
    featuredPlaceCount,
    affinityCount,
  ] = await Promise.all([
    prisma.user.count(),
    prisma.source.count(),
    prisma.activity.count(),
    prisma.activity.count({ where: { kind: 'EVENT' } }),
    prisma.activity.count({ where: { kind: 'PLACE' } }),
    prisma.activity.count({ where: { kind: 'EVENT', isFeatured: true } }),
    prisma.activity.count({ where: { kind: 'PLACE', isFeatured: true } }),
    prisma.userCategoryAffinity.count({ where: { userId: user.id } }),
  ]);

  console.log({
    users: userCount,
    sources: sourceCount,
    activities: activityCount,
    events: eventCount,
    places: placeCount,
    featuredEvents: featuredEventCount,
    featuredPlaces: featuredPlaceCount,
    affinities: affinityCount,
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
