import type { CSSProperties } from 'react';

export const filterStyles: Record<string, CSSProperties> = {
  bar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    padding: '1rem',
    width: '100%',
    maxWidth: 280,
    background: '#F2EBE0',
    borderRadius: 12,
    fontFamily: 'system-ui, sans-serif',
    color: '#0E0F12',
  },
  group: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  legend: {
    fontSize: '0.75rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: '#5A5C66',
    margin: 0,
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.375rem',
  },
  chip: {
    padding: '0.375rem 0.75rem',
    borderRadius: 9999,
    border: '1px solid #E5DED1',
    background: '#FFFFFF',
    color: '#0E0F12',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  chipSelected: {
    background: '#0E0F12',
    color: '#FFFFFF',
    borderColor: '#0E0F12',
  },
  rangeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  input: {
    flex: 1,
    minWidth: 0,
    padding: '0.375rem 0.5rem',
    borderRadius: 6,
    border: '1px solid #E5DED1',
    background: '#FFFFFF',
    color: '#0E0F12',
    fontSize: '0.875rem',
  },
  numberInput: {
    width: '100%',
    padding: '0.375rem 0.5rem',
    borderRadius: 6,
    border: '1px solid #E5DED1',
    background: '#FFFFFF',
    color: '#0E0F12',
    fontSize: '0.875rem',
  },
};
