import type { CSSProperties } from 'react';

export const filterStyles: Record<string, CSSProperties> = {
  bar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    padding: 0,
    width: '100%',
    fontFamily: 'var(--font-body)',
    color: 'var(--ink)',
  },
  group: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    border: 0,
    padding: 0,
    margin: 0,
  },
  legend: {
    fontSize: '0.7rem',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    color: 'var(--smoke)',
    margin: 0,
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.375rem',
  },
  chip: {
    padding: '0.375rem 0.75rem',
    borderRadius: 9999,
    border: '1px solid var(--line)',
    background: 'var(--offwhite)',
    color: 'var(--ink)',
    fontSize: '0.8125rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  chipSelected: {
    background: 'var(--ink)',
    color: 'var(--offwhite)',
    borderColor: 'var(--ink)',
  },
  chipDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  rangeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  input: {
    flex: 1,
    minWidth: 0,
    padding: '0.375rem 0.5rem',
    borderRadius: 8,
    border: '1px solid var(--line)',
    background: 'var(--offwhite)',
    color: 'var(--ink)',
    fontSize: '0.8125rem',
    fontFamily: 'inherit',
  },
  numberInput: {
    width: '100%',
    padding: '0.375rem 0.5rem',
    borderRadius: 8,
    border: '1px solid var(--line)',
    background: 'var(--offwhite)',
    color: 'var(--ink)',
    fontSize: '0.8125rem',
    fontFamily: 'inherit',
  },
};
